### ISSUE TITLE
The license is non-free

### ISSUE THREAD

**Issue by bowlofeggs** [oli-obk/rust-si#17]
Greetings!

I see that you are using a custom license that includes the restriction "The Software may not be used in
any system whose intent is harm any person's privacy, body or mind." I am not a laywer, but this seems similar to the [JSON license](http://www.json.org/license.html)'s clause that the software must be used for good and not evil. You can use a web search to find analysis on why that license is considered non-free.

Though the goal does seem good, one of the problems with the text is that it does not define what "harm" is (similar to how "evil" and "good" are not easy to define in the JSON license).

I recommend relicensing under an [OSI approved license](https://opensource.org/licenses).

**Comment by oli-obk** [comment]
This is kinda on purpose. If someone worries about whether the term "intent to harm" applies to them, it does.

I don't really have an issue with going to a free license. If someone makes a relicense PR with checkboxes for all past, present and future contributors, I'll merge it without complaint.

**Comment by bowlofeggs** [comment]
Do you really mean to include future contributors as a criteria for relicensing?

**Comment by oli-obk** [comment]
lol, no, sorry. But the license change should include wording so that any contributions (past and future) are under e.g. Apache2 + MIT licenses.

**Comment by bowlofeggs** [comment]
Cool. For past contributors, we can try to see if we can contact them to ask if they are willing to switch to a free license. For future contributors, I recommend using the [DCO](https://developercertificate.org/) - it's just a way for contributors to certify that their patch is FOSS and more explicitly, that they grant it to the project under the same license as the project.

**Comment by bowlofeggs** [comment]
Greetings contributors! I propose relicensing this project under an OSI approved license. Could each of you reply with a set of OSI licenses that you would agree with relicensing your past contributions under? If there are some common licenses that you can all agree to, then we can pick that one. @oli-obk suggested Apache 2.0 or MIT above, for example.

CC @oli-obk @nakeep @chrisxue815 @quadfault @Ryman 

@oli-obk The early commits in the repo were from Oliver Schneider - is that you? That's the only name I saw that I didn't CC above.

**Comment by chrisxue815** [comment]
I don't mind. Any OSI license works for me.

**Comment by bowlofeggs** [comment]
I'll keep a record here for contributors we have heard from:

- [x] @chrisxue815 - Any OSI license
- [ ] @oli-obk 
- [ ] @nakeep 
- [ ] @quadfault 
- [ ] @Ryman

**Comment by quadfault** [comment]
Any is fine with me.

**Comment by oli-obk** [comment]
> @oli-obk The early commits in the repo were from Oliver Schneider - is that you? 

yes

**Comment by Ryman** [comment]
>  Any OSI license works for me

Same!

**Comment by bowlofeggs** [comment]
Hello @nakeep - are you OK with the proposed license changes?

**Comment by bowlofeggs** [comment]
I have written @nakeep an e-mail to see if they are OK with switching the license here.

For reference, they have written two commits:

https://github.com/oli-obk/rust-si/commits?author=nakeep

**Comment by oli-obk** [comment]
worst case we'll revert their commits and open an issue with the general idea of compile-time checking the correctness

**Comment by qryxip** [comment]
I've just contributed to this repository. I am OK with the license change.

**Comment by Endle** [comment]
Do we have any updates about this progress?

**Comment by oli-obk** [comment]
we could revert @nakeep's commits, their github accounts seems to be dead.

**Comment by Endle** [comment]
I executed such command
```
$ git shortlog --summary --numbered --email
    20  Oliver Schneider <git1984941651981@oli-obk.de>
    19  Oliver Schneider <git-spam-no-reply9815368754983@oli-obk.de>
     9  Oliver Schneider <oli-obk@users.noreply.github.com>
     8  Oliver Scherer <github35764891676564198441@oli-obk.de>
     5  Kevin Butler <haqkrs@gmail.com>
     4  Ryo Yamashita <qryxip@gmail.com>
     3  Breno Viana <bmfviana@gmail.com>
     2  Carl Scherer <Lireer@users.noreply.github.com>
     2  MuhammadAnnaqeeb <annaqeeb@outlook.com>
     2  Oli Scherer <github35764891676564198441@oli-obk.de>
     2  Oliver Schneider <github6541940@oli-obk.de>
     1  Chris Xue <chrisxue815@gmail.com>
     1  Lorenz Gorse <lorenz.gorse@gmail.com>
     1  Oliver Schneider <git-no-reply-9879165716479413131@oli-obk.de>
     1  Oliver Schneider <github333195615777966@oli-obk.de>
     1  Zhenbo Li <3221521+Endle@users.noreply.github.com>
     1  quadfault <quadfault@gmail.com>
```


How can we find the two patches committe by nakeep in this list?

**Comment by oli-obk** [comment]
`git log --author="MuhammadAnnaqeeb <annaqeeb@outlook.com>"` should work

**Comment by Endle** [comment]
Thanks @oli-obk 
I'm trying to revert these two patches and checking if anything would be broken.


```
commit fe2b3b6d436bf02127d2ff37857083a3f98acf15
Author: MuhammadAnnaqeeb <annaqeeb@outlook.com>
Date:   Sat Nov 26 01:16:28 2016 +0200

    add failing examples, add a test for panic
    
    also switch line ending to LF in .gitattributes to avoid failed tests
    because of  line ending changing while cloning repo. Also avoid copying
    .lock file by listing it in .gitignore

commit fda477c20108470178266fcfaae2bde4cdb3ca75
Author: MuhammadAnnaqeeb <annaqeeb@outlook.com>
Date:   Fri Nov 25 06:48:35 2016 +0200

    allow compilation time checks
    
    use format_args!() macro to allow compile time checks. Now code like:
    ```
    let a: i32;
    let b: &mut u8 = &mut 5;
    scan!("{}, {}{", a, *b);
    ```
    will not pass compilation, however code as
    ```
    let a: i32;
    let b: &mut u8 = &mut 5;
    scan!("{:o}, {:o}", a, *b);
    ```
     will pass compilation and fail at runtime
```


Besides, have we tried to connect him by email?

**Comment by oli-obk** [comment]
> Besides, have we tried to connect him by email?

I haven't

**Comment by Endle** [comment]
I'm trying to revert nakeep's first commit by https://github.com/oli-obk/rust-si/pull/35

For the other commit https://github.com/oli-obk/rust-si/commit/fda477c20108470178266fcfaae2bde4cdb3ca75 it seems that his change has been overwritten (partially) by otherchanges

```
$ git blame src/lib.rs | grep -i Muhammad
fda477c2 (MuhammadAnnaqeeb 2016-11-25 06:48:35 +0200 224)     ($text:expr, $($arg:expr),*) => {
fda477c2 (MuhammadAnnaqeeb 2016-11-25 06:48:35 +0200 227)         format_args!($text, $($arg),*);
fda477c2 (MuhammadAnnaqeeb 2016-11-25 06:48:35 +0200 228)     };
```

**Comment by oli-obk** [comment]
I guess just remove

https://github.com/oli-obk/rust-si/blob/b0e8ce70b76ff3348ab1c8ce59a9a492c805acdd/src/lib.rs#L171

and 

https://github.com/oli-obk/rust-si/blob/b0e8ce70b76ff3348ab1c8ce59a9a492c805acdd/src/lib.rs#L209

**Comment by Endle** [comment]
Thanks @oli-obk 
Are we good to go?

**Comment by oli-obk** [comment]
yes

**Comment by Endle** [comment]
Hi @oli-obk , do you plan to change the LICENSE file soon?
Besides, I assume a new release (0.1.9?) is needed, so the metadata on crates.io would be refreshed.
https://crates.io/crates/text_io

**Comment by oli-obk** [comment]
Done!

**Comment by MuhammadAnnaqeeb** [comment]
I am sorry for very late reply. Please go ahead and change the license. Sadly, years went without me seeing the message. My old Github handle was @nakeep.
