### ISSUE TITLE
Travis CI stops working for this project

### ISSUE THREAD

**Issue by Endle** [oli-obk/rust-si#34]
``` 
Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

        Travis CI - Test and Deploy Your Code with Confidence is in read-only mode. The historical data can be downloaded to external file storage.
```
The last successful build for rust_si was in October 2020 https://travis-ci.org/github/oli-obk/rust-si/builds

If anyone create a PR, or we have a new commit, we won't have CI results.

How about
1. Migrate to travis-ci.com   Or
2. Migrate to Github Actions

**Comment by oli-obk** [comment]
I think we should migrate to github actions, they are rather easy to set up after all. Trying now

**Comment by oli-obk** [comment]
Yes, it was easy. Done
