### ISSUE TITLE
BUG | `Read` reimported here - scan macro

### ISSUE THREAD

**Issue by ArtifyCZ** [oli-obk/rust-si#41]
When I try to compile:
fn main() {
    let a: u8;
    let b: u8;
    scan!("{}", a);
    scan!("{}", b);
}
It says:
error[E0252]: the name `Read` is defined multiple times
  --> src\main.rs:46:5
   |
46 |     scan!("{}", a);
   |     ^^^^^^^^^^^^^^^ `Read` reimported here
47 |     scan!("{}", b);
   |     --------------- previous import of the trait `Read` here
   |
   = note: `Read` must be defined only once in the type namespace of this block
   = note: this error originates in the macro `scan` (in Nightly builds, run with -Z macro-backtrace for more info)

I've found out this as a bug, can you fix it please?

**Comment by Quinn1876** [comment]
I have also encountered this. A workaround that I am using is the following:
```
fn main() {
let a: u8;
let b: u8;
{ scan!("{}", a); }
{ scan!("{}", b); }
}
```
