### ISSUE TITLE
text_io 0.1.10 and 0.1.12 fails in older code

### ISSUE THREAD

**Issue by fercsi** [oli-obk/rust-si#45]
I use 0.1.10 in a system, where edition 2021 is not available. However, if I download the dependencies, it tries to download 0.1.12, but it would like to use edition 2021. So I cannot compile my older code in production. This is a serious issue, now.

in my Cargo.toml:

```
...
edition = "2018"

[dependencies]
text_io = "0.1.10"
...
```

But this is what I get when I try to use it:

```
error: failed to download `text_io v0.1.12`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/fercsi/.cargo/registry/src/github.com-1ecc6299db9ec823/text_io-0.1.12/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.

```

**Comment by oli-obk** [comment]
Please use a newer compiler. Even a newer compiler will allow you to use an older edition.

If you want to force a specific version, you can depend on `text_io = "=0.1.10"` in your `Cargo.toml` or use `cargo update -p text_io:0.1.10`

**Comment by fercsi** [comment]
Thank you!
I could manage this issue with "=0.1.10" (I can't change my dev environment).

_Note, that there shouldn't be any compatibility issues from changing 0.1.10 -> 0.1.12._

**Comment by oli-obk** [comment]
> Note, that there shouldn't be any compatibility issues from changing 0.1.10 -> 0.1.12.

yea, once we are able to specify the minimum Rust version in `Cargo.toml` you'd automatically not get any newer versions. Until we get that, I try to support every compiler up to a year old or so. Supporting back further limits us in the features we can use and is thus a maintenance cost.
