### ISSUE TITLE
Is there a way to avoid breaking when entering a wrong input type?

### ISSUE THREAD

**Issue by schnappi21** [oli-obk/rust-si#46]
Hey, I just started using this crate and I was wondering if there's any way to avoid breaking an app when entering the wrong input type for a read() variable, for example:

```rs
    let number: i32 = read!();
```
This would break if I entered anything that's not **i32** for example entering the word *"car"*.

Is there any way of using for example exceptions here? I'm relatively new to Rust and I can't think of a good fix for this.

Thanks in advance! :)

**Comment by oli-obk** [comment]
You can use `try_read!` instead of `read!` which will give you an `Option` that you can `match` on.

**Comment by schnappi21** [comment]
> You can use `try_read!` instead of `read!` which will give you an `Option` that you can `match` on.

Thanks I'll try it out real quick! :)

**Comment by schnappi21** [comment]
Got it working, thanks! :+1:
